import turtle
turt = turtle.Turtle()
turtle.bgcolor("black")
turt.color("white" , "cyan")

turt.begin_fill()
turt.forward(100)
turt.right(90)
turt.forward(100)
turt.right(90)
turt.forward(100)
turt.right(90)
turt.forward(100)
turt.right(90)
turt.forward(100)
turt.end_fill()
turt.begin_fill()

for i in range(3):
    turt.begin_fill()
    turt.forward(100)
    turt.right(90)
    turt.forward(100)
    turt.right(90)
    turt.forward(100)
    turt.end_fill()
    turt.begin_fill()
    turt.left(90)
    turt.forward(100)
    turt.left(90)
    turt.forward(100)
    turt.left(90)
    turt.forward(100)
    turt.right(90)
    turt.end_fill()

turt.end_fill()
turt.penup()
turt.backward(300)
turt.left(90)
turt.forward(300)
turt.pendown()

for i in range(3):
    turt.begin_fill()
    turt.forward(100)
    turt.left(90)
    turt.forward(100)
    turt.left(90)
    turt.forward(100)
    turt.end_fill()
    turt.begin_fill()
    turt.right(90)
    turt.forward(100)
    turt.right(90)
    turt.forward(100)
    turt.right(90)
    turt.forward(100)
    turt.left(90)
    turt.end_fill()

turtle.done()
